name: Map Bundling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Fetch & extract
      run: |
        wget https://github.com/Team-OZE/OZEdit/releases/download/v0.1/OZEdit-Cmd-x86-debug.zip -O /tmp/tool.zip
        unzip /tmp/tool.zip -d /tmp