name: Map Bundling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Fetch & extract
      run: |
        Invoke-WebRequest -OutFile tool.zip https://github.com/Team-OZE/OZEdit/releases/download/v0.1/OZEdit-Cmd-x86-debug.zip
        Expand-Archive -Path tool.zip -DestinationPath tool
    - name: Bundle the map
      run: |
        & "$(Get-Location)\tool\OZEdit.exe" "$(Get-Location)\MapData" "$(Get-Location)\Legion_TD_Release.w3x"